global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: backend-api
    metrics_path: /metrics
    static_configs:
      - targets: ["backend-api:8000"]

  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector:8889"]
